nginx:
  image: nginx
  ports:
    - "8080:80"
    - "443:443"
  volumes:
    - ./src/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php72:fpm

php72:
  build: ./php/php72/
  expose:
    - "9000"
  volumes:
    - ./src/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis
#  mysql:
#    image: mariadb
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example

# 自动执行SQL脚本：https://www.jianshu.com/p/12fc253fa37d
mysql:
  image: mariadb
  ports:
    - "9306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"

redis:
  image: redis:latest
  ports:
    - "6379:6379"
